//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DailyGoalPerWeek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyGoalPerWeek()
        {
            this.Users = new HashSet<User>();
        }
        [Key]
        public int DailyId { get; set; }
        public Nullable<System.DateTime> SundayOfWeek { get; set; }
        public string Calories { get; set; }
        public string Fats { get; set; }
        public string Fibers { get; set; }
        public string Proteins { get; set; }
        public string Sugars { get; set; }
        public string[,] FullGoals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }

        public DailyGoalPerWeek(DateTime aSundayOfWeek,string aCalories, string aFats, string aFibers, string aProteins, string aSugar, string[,] aFullGoals)
        {
            this.Users = new HashSet<User>();
            this.SundayOfWeek = aSundayOfWeek;
            this.Calories = aCalories;
            this.Fats = aFats;
            this.Fibers = aFibers;
            this.Proteins = aProteins;
            this.Sugars = aSugar;
            this.FullGoals = new string[4, 5];
            this.FullGoals = aFullGoals;
        }

        public override string ToString()
        {
            return null;
        }
    }
}
