//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DailyGoalPerWeeks = new HashSet<DailyGoalPerWeek>();
            this.Meals = new HashSet<Meal>();
        }
        [Key]
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string BirthDate { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyGoalPerWeek> DailyGoalPerWeeks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meal> Meals { get; set; }

        public User(string FirstName, string LastName, string EmailAddress, string Password, string DateOfBirth, string Height, string Weight)
        {
            this.DailyGoalPerWeeks = new HashSet<DailyGoalPerWeek>();
            this.Meals = new HashSet<Meal>();
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.EmailAddress = EmailAddress;
            this.Password = Password;
            this.BirthDate = DateOfBirth;
            this.Height = Height;
            this.Weight = Weight;
        }
        public override string ToString()
        {
            return "    name: " + FirstName + "   " + LastName + "   EmailAddress: " + EmailAddress + "     " + "Password: " + Password + "    DateOfBirth: " + BirthDate + "    Height: " + Height + "    Weight: " + Weight;
        }
    }
}
